spawn:
  red:
    world: world
    x: 0
    y: 0
    z: 0
  blue:
    world: world
    x: 0
    y: 0
    z: 0
jail:
  red:
    world: world
    x: 0
    y: 0
    z: 0
    button:
      x: 0
      y: 0
      z: 0
  blue:
    world: world
    x: 0
    y: 0
    z: 0
    button:
      x: 0
      y: 0
      z: 0
